name: testing base64 workflow

on:
  push:
    branches:
     - main

jobs:

  string_to_base64:
    uses: tusharmathur08/officialworkflows/.github/workflows/base64.yaml@base64-workflow
    with:
       string_value: "test"

  fetch_bas64:
    needs: string_to_base64
    runs-on: ubuntu-latest
    steps:

      - name: Display base64 encoded value
        run: |
             echo "${{ needs.string_to_base64.outputs.base64_encoded_value }}"
          
