name: testing base64 workflow

on:
  push:
    branches:
     - main

jobs:
#Calling the reusable workflow directly using "uses:" command where we are providing the input string value as test
  string_to_base64:
  #Need to provide the file destination here, I have provided my workflow file location for this sample worklfow
    uses: tusharmathur08/officialworkflows/.github/workflows/base64.yaml@main
    with:
       string_value: "test"

  fetch_base64:
    needs: string_to_base64
    runs-on: ubuntu-latest
    steps:

      - name: Display base64 encoded value
        run: |
             echo "${{ needs.string_to_base64.outputs.base64_encoded_value }}"
          
